# Generated by Django 3.2.4 on 2024-07-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='categoria',
            field=models.CharField(choices=[('tradicional', 'Tradicional'), ('innovador', 'Innovador'), ('sin_azucar', 'Sin Azúcar')], default='tradicional', max_length=50),
        ),
    ]
