# Generated by Django 3.2.4 on 2024-07-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flan_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flan',
            old_name='categoria',
            new_name='category',
        ),
        migrations.AddField(
            model_name='flan',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flan',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
