# Generated by Django 3.2.4 on 2024-07-20 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20240720_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flan',
            name='flan_uuid',
        ),
    ]
